" use Bash as shell instead Fish shell (fixes incompatibility issues)
set sh=bash

" required for Vundle plugin
set nocompatible
filetype off

" set runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" manage plugin through Vundle
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'spolu/dwm.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive'
Plugin 'evidens/vim-twig'
Plugin 'timcharper/textile.vim'
call vundle#end()

" required for Vundle plugin
filetype plugin indent on


" ===============
" PLUGIN SETTINGS
" ===============

" AIRLINE
" -------
set laststatus=2
set t_Co=256
let g:airline_theme='solarized'

" SYNTASTIC
" ---------
let g:syntastic_cpp_compiler_options = '--std=c++11'
let g:syntastic_cpp_check_header = 1
let g:syntastic_sass_checkers=['']
let g:syntastic_scss_checkers=['']


" ===============
" CUSTOM SETTINGS
" ===============
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set number

set cursorline

set textwidth=79
set nowrap

" enable highlight search
set hls

" map CTRL+n to open NERDTree plugin
map <C-t> :NERDTreeToggle<CR>

" force markdown syntax highlight for *.md files
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" disable column width for Textile/(La)Tex files, also disable line numbering
autocmd BufNewFile,BufReadPost *.text* set textwidth=0 nonumber

" vim solarized theme
syntax enable
colorscheme solarized
set background=dark
