" teach Vim to fish...
if &shell =~# 'fish$'
    set shell=sh
endif

" required for Vundle plugin
set nocompatible
filetype off

" set runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" manage plugin through Vundle
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'spolu/dwm.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'altercation/vim-colors-solarized'
Plugin 'tpope/vim-fugitive'
Plugin 'evidens/vim-twig'
Plugin 'vim-scripts/click.vim'
Plugin 'dln/avro-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'AlxHnr/latex_preview'
Plugin 'dylon/vim-antlr'
Plugin 'Valloric/YouCompleteMe'
call vundle#end()

" required for Vundle plugin
filetype plugin indent on


" ===============
" PLUGIN SETTINGS
" ===============

" AIRLINE
" -------
set laststatus=2
set t_Co=256
let g:airline_theme='solarized'

" SYNTASTIC
" ---------
let g:syntastic_cpp_compiler_options='--std=c++11'
let g:syntastic_cpp_check_header=1
let g:syntastic_cpp_no_default_include_dirs=0
let g:syntastic_cpp_include_dirs=['include', 'lib']
let g:syntastic_mode_map = {'passive_filetypes': ['sass', 'scss']}

" VIM MARKDOWN
" ------------
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_frontmatter = 1

" YOUCOMPLETEME
" -------------
let g:ycm_server_python_interpreter = '/usr/bin/python'
let g:ycm_autoclose_preview_window_after_completion = 1


" ===============
" CUSTOM SETTINGS
" ===============
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set number

set cursorline

set textwidth=79
set nowrap
set linebreak

" enable highlight search
set hls

" map CTRL+n to open NERDTree plugin
map <C-t> :NERDTreeToggle<CR>

" force syntax highlighting by setting the filetype
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd BufNewFile,BufReadPost *.click set filetype=click
autocmd BufNewFile,BufReadPost *.tex set filetype=tex
autocmd BufNewFile,BufReadPost *.avdl set filetype=avro-idl
autocmd BufNewFile,BufReadPost *.avsc set filetype=json
autocmd BufNewFile,BufReadPost *.avpr set filetype=json
autocmd BufNewFile,BufReadPost *.g set filetype=antlr3
autocmd BufNewFile,BufReadPost *.g4 set filetype=antlr4

" vim solarized theme
syntax enable
colorscheme solarized
set background=light
